In [8]:
# 
# Междивизион
#


from sqlalchemy import create_engine
from sqlalchemy import insert
from datetime import timedelta
from datetime import datetime
from datetime import date
import pandas as pd
import numpy as np
from pandas import pivot_table
from shutil import copyfile


date_x = datetime.now()-timedelta(0)                          # Внимание! Проверить смещение!!
date_first = date_x - timedelta(35)
date_last = date_x 
date_stfirst = date_x - timedelta(34)
date_stlast = date_x - timedelta(-1)

date_first_w = date_x - timedelta(7)
date_last_w = date_x - timedelta(1)
date_stfirst_w = date_x - timedelta(6)
date_stlast_w = date_x - timedelta(-1)

display('Начинаю работать...')
display("Стартовый день: ")
display(date_x)


engine = create_engine('postgresql://awsuser:67Gh$5aP#@redshift-cluster-1.c9nv0atgk8dm.eu-west-1.redshift.amazonaws.com:5439/adata')

id=engine.execute("INSERT INTO  log (work , datetime, comment) VALUES ('Междивизион',  CURRENT_TIMESTAMP, 'start')")

# Стартовый блок, за 5 недель

sql = """
select
	*
from
	(
	select
		f.feature_id,
		group_name as group ,
		subgroup_name as subgroup ,
		category_name as category ,
		subcategory_name as subcategory ,
		trim(m.model_id) as model_id ,
		m.modelname ,
		f.code,
		m.code as fullmodelcode ,
		c."name" as colorname,
		uuid as foto ,
		sz."name" as ssize,
		'1' as crm ,
		m.season ,
		status ,
		CASE WHEN new_price <> 0 THEN 1 ELSE 0 END AS sale
/*		f.firstcolorcode as colorcode ,
		trim(m.model_id)+ ';' + c."name" as service ,
		min as first_date , 
		codes   */
	from
		(
		select
			*
		from
			(
				SELECT DISTINCT feature_id FROM public.sales where datetime between '""" + date_first.strftime("%Y-%m-%d") + """' and '""" + date_x.strftime("%Y-%m-%d") + """'
        union
        SELECT DISTINCT feature_id FROM stocks where datetime between '""" + date_stfirst.strftime("%Y-%m-%d") + """' and '""" + date_stlast.strftime("%Y-%m-%d") + """' and quantity <> 0 )
		group by
			feature_id ) as b
	join features f on
		b.feature_id = f.feature_id
	join colors c on
		f.color_id = c.color_id
	join sizes sz on
		f.size_id = sz.size_id 	
	left join persisted_hierarchy ph on
		f.model_id = ph.model_id
	join models m on
		f.model_id = m.model_id
	left join block_first_selling_date bfsd on
		f.model_id = bfsd.model_id
		and c."name" = bfsd.color 
	left join (
				select * from discounts d where '""" + date_x.strftime("%Y-%m-%d") + """' >= timefrom and '""" + date_x.strftime("%Y-%m-%d") + """' < timeto
			) as a on m.model_id = a.model_id and c."name" = a.colorname	
		)
where
	"group" <> '4. Подарочные сертификаты'
	and "group" <> '5. Тест'
	and "group" <> '6. Продукты'
	and "group" <> '7. Образцы'
	and "group" <> '8. Канцелярия'



"""

print(sql.replace('\t', ' ').replace('\n', ' '))

df = pd.read_sql_query(sql, engine)

df = df.drop_duplicates(subset=['model_id', 'colorname'], keep='first')

df = df.sort_values(['group', 'subgroup', 'category', 'subcategory', 'modelname', 'colorname'])

display(df)

# Данные по остаткам и продажам

'Начинаю работать...'

'Стартовый день: '

datetime.datetime(2021, 12, 26, 10, 28, 31, 598264)

 select  * from  (  select   f.feature_id,   group_name as group ,   subgroup_name as subgroup ,   category_name as category ,   subcategory_name as subcategory ,   trim(m.model_id) as model_id ,   m.modelname ,   f.code,   m.code as fullmodelcode ,   c."name" as colorname,   uuid as foto ,   sz."name" as ssize,   '1' as crm ,   m.season ,   status ,   CASE WHEN new_price <> 0 THEN 1 ELSE 0 END AS sale /*  f.firstcolorcode as colorcode ,   trim(m.model_id)+ ';' + c."name" as service ,   min as first_date ,    codes   */  from   (   select    *   from    (     SELECT DISTINCT feature_id FROM public.sales where datetime between '2021-11-21' and '2021-12-26'         union         SELECT DISTINCT feature_id FROM stocks where datetime between '2021-11-22' and '2021-12-27' and quantity <> 0 )   group by    feature_id ) as b  join features f on   b.feature_id = f.feature_id  join colors c on   f.color_id = c.color_id  join sizes sz on   f.size_id = sz.size_id    left join persisted_hierarchy ph on   f.model_id = ph.model_id  join models m on   f.model_id = m.model_id  left join block_first_selling_date bfsd on   f.model_id = bfsd.model_id   and c."name" = bfsd.color   left join (     select * from discounts d where '2021-12-26' >= timefrom and '2021-12-26' < timeto    ) as a on m.model_id = a.model_id and c."name" = a.colorname    ) where  "group" <> '4. Подарочные сертификаты'  and "group" <> '5. Тест'  and "group" <> '6. Продукты'  and "group" <> '7. Образцы'  and "group" <> '8. Канцелярия'

,feature_id,group,subgroup,category,subcategory,model_id,modelname,code,fullmodelcode,colorname,foto,ssize,crm,season,status,sale
2886,24598da0-5132-11ec-911a-7085c281e0ea,1. Одежда,1.1 Поясные,1.1.1 Брюки и леггинсы,1.1.1.1 Брюки классические,ЦБ-00003745,Брюки базовые 2,31359,1WPT/009328,Серый,efd00748-5131-11ec-911a-7085c281e0ea,44,1,None,,0
2443,01eff7b6-5132-11ec-911a-7085c281e0ea,1. Одежда,1.1 Поясные,1.1.1 Брюки и леггинсы,1.1.1.1 Брюки классические,ЦБ-00003745,Брюки базовые 2,31353,1WPT/009328,Черный,efd00748-5131-11ec-911a-7085c281e0ea,40,1,None,Фотосессия 21_092,1
193,fc53fe4b-b6e4-11ea-9107-7085c281e0ea,1. Одежда,1.1 Поясные,1.1.1 Брюки и леггинсы,1.1.1.1 Брюки классические,ЦБ-00001420,Брюки белые,24299,1WPT/006662,Белый,dedd7f69-b6e4-11ea-9107-7085c281e0ea,42,1,None,Фотосессия 6,1
188,74b99446-3500-11ea-9103-7085c281e0ea,1. Одежда,1.1 Поясные,1.1.1 Брюки и леггинсы,1.1.1.1 Брюки классические,ЦБ-00000975,Брюки зауженные,21745,1WPT/006348,Коричневый,5673065f-3500-11ea-9103-7085c281e0ea,46-48,1,None,Фотосессия 2,1
3258,ae815f08-6496-11eb-9111-7085c281e0ea,1. Одежда,1.1 Поясные,1.1.1 Брюки и леггинсы,1.1.1.1 Брюки классические,ЦБ-00002379,Брюки классика с 2мя карманами,26879,1WPT/007501,Бежевый,cfaa4bc6-648e-11eb-9111-7085c281e0ea,40-42,1,None,Фотосессия 21_079,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,d586bd6a-205c-11ec-9118-7085c281e0ea,3. Аксессуары,3.1 Аксессуары,3.1.9 Прочие аксессуары,"3.1.9.1 Носки, колготки (ЧНИ)",ЦБ-00003458,Носки однотонные,30535,3АOH/000054,Серый,b11e93c0-205c-11ec-9118-7085c281e0ea,one size,1,None,Фотосессия 21_079,1
2229,3f417f49-2061-11ec-9118-7085c281e0ea,3. Аксессуары,3.1 Аксессуары,3.1.9 Прочие аксессуары,"3.1.9.1 Носки, колготки (ЧНИ)",ЦБ-00003458,Носки однотонные,30540,3АOH/000054,Темно-серый,b11e93c0-205c-11ec-9118-7085c281e0ea,one size,1,None,Фотосессия 21_079,1
2946,fdf00c48-493c-11ec-911a-7085c281e0ea,3. Аксессуары,3.1 Аксессуары,3.1.9 Прочие аксессуары,"3.1.9.1 Носки, колготки (ЧНИ)",ЦБ-00003713,Носки с логотипом,31281,3АOH/009302,Белый,ede77c37-493c-11ec-911a-7085c281e0ea,one size,1,None,,0
2430,4a9fde3a-275c-11ec-9118-7085c281e0ea,3. Аксессуары,3.1 Аксессуары,3.1.9 Прочие аксессуары,"3.1.9.1 Носки, колготки (ЧНИ)",ЦБ-00003503,Носки с широкими полосками 2,30675,3АOH/000099,Белый,421649b8-275c-11ec-9118-7085c281e0ea,one size,1,None,Фотосессия 21_084,0
692,50ca341c-275c-11ec-9118-7085c281e0ea,3. Аксессуары,3.1 Аксессуары,3.1.9 Прочие аксессуары,"3.1.9.1 Носки, колготки (ЧНИ)",ЦБ-00003503,Носки с широкими полосками 2,30676,3АOH/000099,Черный,421649b8-275c-11ec-9118-7085c281e0ea,one size,1,None,Фотосессия 21_084,0